version: '3.8'
services:
  database:
    image: postgres
    hostname: database
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - ./migrations_docker/init.sql:/docker-entrypoint-initdb.d/init.sql
  app:
    build: .
    depends_on:
      database:
        condition: service_healthy
    hostname: app
    environment:
    # Set only if you want to choose spicific path
      CONFIG_PATH_DOCKER: ${DOCKER_CONFIG_PATH}
    ports:
      - "8081:8081"
