version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:managment
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER=rmuser
      RABBITMQ_DEFAULT_PASS=rmpassword
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics -q ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
  ms:
    build: .
    hostname: mail_sender
    environment:
      DOCKER_CONFIG_PATH: "config/server_docker.toml"
    depends_on:
      rabbitmq:
        condition: service_healthy
