version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:management
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics check_port_connectivity"]
      interval: 30s
      timeout: 30s
      retries: 1
      start_period: 40s
    ports:
      - "5672:5672"
      - "15672:15672"
  ms:
    build: .
    hostname: mail_sender
    environment:
      DOCKER_CONFIG_PATH: ${DOCKER_CONFIG_PATH}
    depends_on:
      rabbitmq:
        condition: service_healthy
